[tool.poetry]
name = "coups"
version = "0.1.0"
description = ""
authors = ["m-quick <martinquick7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
numpy = "^2.1.2"
seaborn = "^0.13.2"
matplotlib = "^3.9.2"
statsmodels = "^0.14.4"
scikit-learn = "^1.5.2"
requests = "^2.32.3"
pre-commit = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
